- name: nginx install
  hosts: localhost
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
       -name: nginx
       state: present
  

  - name: run nginx
    ansible.buitin.service:
       -name: nginx
       state: started
       enabled: yes